#!bin/bash
IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
git clone https://github.com/najahiiii/aarch64-linux-gnu.git -b linaro8-20190216 gcc
git clone https://github.com/najahiiii/clang.git -b llvm9 llvm9
GCC="$(pwd)/gcc/bin/aarch64-linux-gnu-"
CT="$(pwd)/llvm9/bin/clang"
curl -s -F chat_id=-1001229936519 -F sticker="CAADBQAD0AADfULDLtrtiR6t9hoyFgQ" https://api.telegram.org/bot972733242:AAGkE_A52TAqVp-OtdsDHgnxtGHqqP10Zq8/sendSticker
curl -s -X POST https://api.telegram.org/bot972733242:AAGkE_A52TAqVp-OtdsDHgnxtGHqqP10Zq8/sendMessage?chat_id=-1001229936519 -d "disable_web_page_preview=true" -d "parse_mode=html&text=<b>WinXKernel Google</b> new build is up"'!'"%0AFor device <b>RIVA</b> (Redmi 5A)%0AUnder commit <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0A<b>Compiler</b> <code>$(${GCC}gcc --version | head -n 1)</code>%0A<b>Clang</b> <code>$(${CT} --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')</code>%0AStarted on <code>$(date)</code>%0A<b>Build Status:</b> #untested"
tanggal=$(date +'%H%M-%d%m%y')
START=$(date +"%s")
export ARCH=arm64
export KBUILD_BUILD_USER=Yusuf
export KBUILD_BUILD_HOST=Tikom
export USE_CCACHE=1
export CACHE_DIR=~/.ccache
# Fin Error
function finerr() {
        curl -s -X POST https://api.telegram.org/bot972733242:AAGkE_A52TAqVp-OtdsDHgnxtGHqqP10Zq8/sendMessage?chat_id=-1001229936519 -d "disable_web_page_preview=true" -d "parse_mode=html&text=Build throw an error(s)"
        exit 1
}
make -s -C $(pwd) O=out winx_defconfig
make -s -C $(pwd) CC=${CT} CROSS_COMPILE=${GCC} O=out -j32 -l12
if ! [ -a $IMAGE ]; then
	finerr
	exit 1
fi
cp out/arch/arm64/boot/Image.gz-dtb AnyKernel/zImage
cd AnyKernel
zip -r9 Tikom-Slow-lur-${tanggal}.zip *
END=$(date +"%s")
DIFF=$(($END - $START))
curl -F chat_id="-1001229936519" -F document=@"Tikom-slow-lur-${tanggal}.zip" -F "disable_web_page_preview=true" -F "parse_mode=html" -F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s). | #rolex" https://api.telegram.org/bot972733242:AAGkE_A52TAqVp-OtdsDHgnxtGHqqP10Zq8/sendDocument
cd ..
rm -rf out
rm -rf AnyKernel/zImage
rm -rf AnyKernel/Tikom*.zip
